AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - db/schema.rb
    - db/statistics_schema.rb
    - db/potok_investors_schema.rb
    - db/migrate/*
    - db/statistics_migrate/*
    - db/potok_investors/migrate/*
    - bin/*
    - vendor/bundle/**/*
    - provision/**/*
    - was_trs.rb
    - lib/pc/**/*

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Rails/HttpPositionalArguments:
  Enabled: false
